FROM nginx:1.31.5@sha256:05b8cb60c354a44ab824ea6e7dc69b46d50762cdbe728a347a5b656e6fb3d7c4

COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/

RUN test -f /etc/nginx/conf.d/10_site.conf
